# Generated by Django 3.1.7 on 2021-11-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
