# Generated by Django 3.1.7 on 2021-11-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
