# Generated by Django 3.1.7 on 2021-11-23 08:17

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='covers/category/')),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('cover', easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='covers/subscription/')),
                ('description', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('days', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mode',
        ),
        migrations.AddField(
            model_name='user',
            name='payed_until',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('cover', easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='covers/music/')),
                ('description', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category')),
            ],
        ),
    ]
