# Generated by Django 3.1.7 on 2021-11-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
