# Generated by Django 3.1.7 on 2021-11-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
