# Generated by Django 3.1.7 on 2021-11-27 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_verification_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(choices=[(0, 'morning'), (1, 'noon'), (2, 'night')])),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='time_of_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.timeofday'),
        ),
    ]
