# Generated by Django 3.1.7 on 2021-11-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211127_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='file',
            field=models.FileField(null=True, upload_to='musics/'),
        ),
        migrations.AlterField(
            model_name='timeofday',
            name='key',
            field=models.IntegerField(choices=[(0, 'morning'), (1, 'noon'), (2, 'night'), (3, 'no time')]),
        ),
    ]
