# Generated by Django 3.1.7 on 2021-11-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='premium',
            field=models.BooleanField(default=True),
        ),
    ]
