# Generated by Django 3.1.7 on 2021-11-30 07:28

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_music_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('caption', models.TextField(max_length=5000, null=True)),
                ('cover', easy_thumbnails.fields.ThumbnailerImageField(upload_to='covers/article/')),
                ('time', models.IntegerField()),
            ],
        ),
    ]
