# Generated by Django 3.1.7 on 2021-12-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofday',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
