# Generated by Django 3.1.7 on 2021-12-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_timeofday_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
